version: "3.9"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-app
        restart: unless-stopped
        volumes:
            - .:/var/www
        networks:
            - laravel
        depends_on:
            - mysql

    nginx:
        image: nginx:1.25
        container_name: laravel-nginx
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
        networks:
            - laravel
        depends_on:
            - app

    mysql:
        image: mysql:8
        container_name: laravel-mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        ports:
            - "3306:3306"
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
