name: Laravel CI with Docker Compose

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  laravel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and start containers
        run: docker compose up -d --build

      - name: Wait for MySQL
        run: |
          for i in {1..30}; do
            docker compose exec -T app php -r "try { new PDO('mysql:host=mysql;dbname=laravel','laravel','secret'); echo 'DB OK'; exit; } catch (Exception \$e) { echo 'waiting...'; }" || true
            sleep 5
          done

      - name: Run migrations
        run: docker compose exec -T app php artisan migrate --force

      - name: Run tests
        run: docker compose exec -T app php artisan test

      - name: Push Laravel App Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: your-dockerhub-username/laravel-app:latest
